### ISSUE TITLE
Toolbar button is initially incorrect

### ISSUE THREAD

**Issue by jnm2** [tunnelvisionlabs/JustMyCodeToggle#13]
Opened VS, started debugging, opened options without changing anything:

![image](https://user-images.githubusercontent.com/8040367/36982315-94a81ec4-205d-11e8-9060-f43e91689667.png)

After clicking, the icon stays untoggled (because it toggled, like it is supposed to).

I think this is what was behind https://github.com/tunnelvisionlabs/JustMyCodeToggle/issues/12. I don't know why I worked around this so long without reporting it—keyboard shortcut makes life easy, I guess! 😄

**Comment by jnm2** [comment]
I debugged the extension and it's immediately obvious that this is due to the package not initializing until the command is activated. @sharwell This still catches me and I've seen it catch a coworker recently. I'd love to make it autoload. What do you think?

**Comment by jnm2** [comment]
At the end of the day, I like looking at the button to see if it's on.

**Comment by jcansdale** [comment]
Alternatively, we could have two `JustMyCodeToggle` related commands, `EnableJustMyCode` and `DisableJustMyCode`. Their initial visibility would be determined by a `UserSettingsStoreQuery` that looks at the users settings to to see if  `JustMyCode` is enabled or not.

See:
https://docs.microsoft.com/en-gb/visualstudio/extensibility/how-to-use-rule-based-ui-context-for-visual-studio-extensions

`EnableJustMyCode` would only be enabled when `JustMyCode` is disabled. `DisableJustMyCode` would only be enabled when `JustMyCode` is enabled. You could give them appropriate icons and tooltips so you can see its state without auto-loading its package.

Does that make sense?

**Comment by jcansdale** [comment]
I dare say if you convert it to be an `AsyncPackage` and used the following, it wouldn't hurt too much. 😉 
```cs
[ProvideAutoLoad(VSConstants.UICONTEXT.SolutionExistsAndFullyLoaded_string, PackageAutoLoadFlags.BackgroundLoad)]
```
